# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Supercard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Supercard
  pod 'AppCenter/Push', '~> 1.8.0'
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  platform :ios, '9.0'


  target 'SupercardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Supercard-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Supercard-tvOS

  target 'Supercard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
